#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

# Initialize the counter variable to 1
counter=1

# Loop until the counter is greater than 10
until [ $counter -gt 10 ]
do
  # Print "Best School" to the standard output
  echo "Best School"

  # Increment the counter by 1
  ((counter++))
done
