#!/usr/bin/env bash
# This script configures an Ubuntu server to change localhost and facebook.com IP addresses.

# Change localhost IP to 127.0.0.2
echo "Setting localhost IP to 127.0.0.2"
sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts

# Change facebook.com IP to 8.8.8.8
echo "Setting facebook.com IP to 8.8.8.8"
sudo sed -i 's/157.240.11.35/8.8.8.8/' /etc/hosts
